site_name: 白杨的文档站
site_url: https://whiteboard-ui8.pages.dev/
site_description: 本站用于收纳一些 FOSS 新闻/博客译文和站长的杂谈、笔记和博客等内容。
site_author: Poplar at twilight

#repo_name: RSS Subscribe
#repo_url: https://whiteboard-ui8.pages.dev/feed_rss_created.xml  #RSS 链接
#edit_uri: ""

theme:
    name: material
    #custom_dir: overrides
    language: zh    
    highlightjs: true
    palette:
      - scheme: default
        primary: green
        accent: blue
        toggle:
          icon: material/brightness-7
          name: 切换到深色模式
      - scheme: slate
        primary: blue
        accent: light green
        toggle:
          icon: material/brightness-4
          name: 切换到浅色模式
    features:
      - navigation.tabs
      - content.tabs.link #启用内容页
      - navigation.footer
      - header.autohide  #公告栏
      - announce.dismiss #可关闭的公告栏
    logo: assets/open-book.png
    #icon:
      #repo: fontawesome/brands/linux
    font:
      text: Noto Sans
      code: Noto Sans Mono    

nav:
    - 首页:
      - index.md
      - about/tags.md
    - 博客:
      - blog/index.md
    - 译文归档:
      - translation/about.md
      - 2024-05:
        - translation/fedora40-release-party.md
        - translation/gimp-2.10.38-released.md
        - translation/gimp-lgm-2024.md
        - translation/fedora-asahi-remix-40-released.md
        - translation/gimp-appimage-test.md
      - 2024-04:
        - translation/tdf-libreoffice-german.md
        - translation/archive.org-aruba-1.md
        - translation/fedora-cve-2024-3094.md
        - translation/fedora-chat.md
        - translation/fedora40-released.md
        - translation/fedora40-whatnew.md
        - translation/fedora40-whatnew-kde.md
        - translation/fedora40-atomic-update.md
      - 2024-03:
        - translation/fedora-flock-2024-cfp.md
        - translation/fedora40-beta-released.md
      - 2024-02:
        - translation/fedora-flock-2024.md
        - translation/fedora-atomic-de-intro.md
        - translation/xfce4-wayland-roadmap.md
        - translation/opensuse-agama-roadmap-2024.md
        - translation/gimp-2.99.18-released.md
      - 2023-12:
        - translation/fedora-asahi-remix-39.md
      - 2023-11:
        - translation/tdf-2023-10-recap.md
        - translation/fedora39-released.md
        - translation/fedora39-whatnew.md
        - translation/gimp-2.10.36-relased.md
      - 2023-10:
        - translation/thunderbird-ransomware-alert.md
        - translation/tdf-2023-09-recap.md
        - translation/fedora-operations-architect.md
        - translation/krita-in-store.md
        - translation/thunderbird-sha-1.md
      - 2023-09:
        - translation/tdf-2023-08-recap.md
        - translation/tdf-libreoffice7.5.6-released.md
        - translation/open-letter-cc-gai.md
        - translation/tdf-1.5million.md
        - translation/kde-wayland.md
        - translation/fedora39-beta-released.md
        - translation/tdf-gsoc-2023.md
      - 2023-08:
        - translation/thunderbird-2023-08-01.md
        - translation/tdf-the-new-goodie-site.md
        - translation/tdf-2023-07-recap.md
        - translation/fedora-asahi-remix.md
        - translation/tdf-2022-annual-report.md
        - translation/blender-2022-annual-report.md
        - translation/tdf-draw-impress-guide-7.5.md
        - translation/gimp-support-arm.md
        - translation/tdf-weblate.md
        - translation/tdf-libreoffice-7.6.md
        - translation/thunderbird-2023-08-25.md
      - 2023-07:
        - translation/wikipedia-llicense-update.md
        - translation/wikimedia-flickr.md
        - translation/gimp-2.99.16-released.md
        - translation/thunderbird-supernova.md
        - translation/2023-07-12-opensuse-faq.md
        - translation/tdf-libreoffice-7.5-new-guideline.md
        - translation/tdf-libreoffice7.5.5-released.md
        - translation/thunderbird-security-audit.md
        - translation/interpeer-wei.md
        - translation/our-world-in-data.md
      - 2023-06:
        - translation/tdf-libreoffice7.5.4.md
        - translation/thunderbird-2023-06-16.md
        - translation/2023-06-18-theevilskeleton.md
        - translation/tdf-thunderbird.md
        - translation/gimp-wilber-week-2023.md
        - translation/blender-3.6-lts.md
        - translation/blender-annecy-2023.md
      - 2023-05:
        - translation/thunderbird-new-logo.md
        - translation/opensuse-aeon.md
        - translation/fedora38-release-party.md    
      - 2023-04:
        - translation/archive.org-2023-0402.md
        - translation/krita-2022-review.md
        - translation/fedora38-released.md
        - translation/fedora38-whatnew.md
        - translation/anaconda-survey-results.md
      - 2023-03:
        - translation/fosdem2023-02.md
        - translation/opensuse-kubic.md
        - translation/fedora38-beta-released.md
        - translation/blender-gdc-2023.md
        - translation/gimp-in-gsoc-2023.md
        - translation/fedora-objective-review.md
      - 2023-02:
        - translation/display-hdr-hackfest.md
        - translation/flathub-linux-app-store.md
      - 2023-01:
        - translation/docker-and-fedora-37.md
        - translation/blender-2023-01.md
        - translation/anaconda-need-feedback.md
        - translation/fedora-fosdem-2023.md
        - translation/Blenderheads.md
        - translation/gimp-2022-annual-report.md
      - 2022-12:
        - translation/xfce4.18-pre2.md
        - translation/yast-d-installer-02.md
        - translation/xfce4.18-released.md
        - translation/fedora-site-merge.md
        - translation/forgejo-2022-12-15.md
        - translation/fedora-get-ready-for-2023.md
      - 2022-11:
        - translation/fedora37-released.md
        - translation/fosdem2023.md
        - translation/gimp-happy-27.md
        - translation/anaconda-webui-image-go-public.md
      - 2022-10:
        - translation/intro-nvk.md
        - translation/using-btrfs-01.md
        - translation/gimp-dev.md
        - translation/2022-10-18-theevilskeleton.md
        - translation/fedora-remains-community-driven.md
        - translation/xfce-4.18-wallpaper-contest.md
        - translation/fedora37-update-note.md
      - 2022-09:
        - translation/fedora37-beta-released.md
        - translation/fedora-38-wallpaper-winner.md
      - 2022-08:
        - translation/libadwaita-gtk4-TheEvilSkeleton.md
        - translation/siggraph-2022-report-blender.md
      - 2022-07:
        - translation/ms-pluton-chips.md
      - 2022-06:
        - translation/gimp-gsoc-2022-02.md
        - translation/open-letter-intel-fsp.md
        - translation/nodejs-eol-v16-0626.md
        - translation/accessibility-in-fedora.md
      - 2022-05:
        - translation/fedora36-released.md
        - translation/2022-05-17-theevilskeleton.md
        - translation/blender-events-in-2022.md
      - 2022-04:
        - translation/yast-d-installer.md
        - translation/xfce4-terminal-1.0.0.md
        - translation/xfce-setting-gui.md
      - 2022-03:
        - translation/xfce4-terminal-0.9.2.md
        - translation/gimp-gsoc-2022.md
        - translation/blender-3.1.md
        - translation/xfce-gsoc-2022.md
        - translation/tdf-libreoffice-gsoc-2022.md
        - translation/plan-to-drop-soft.o.o.md
        - translation/openSUSE-code-of-conduct.md
      - 2022-02:
        - translation/donation-help-us.md
      - 2022-01:
        - translation/xfce-2022-01-21.md
      - 2021-10:
        - translation/gimp-mirror-policy.md
      - 2021-12:
        - translation/xfce-2021-12-10.md
        - translation/eff-chrome-manifestv3.md
      - 2021-11:
        - translation/fedora35-released.md
        - translation/xfce-2021-11-26.md
      - 2021-10:
        - translation/kde-network-china-2021.md
      - 2021-09:
        - translation/xfce-2021-09-12.md
        - translation/xfce-09-17.md
        - translation/fedora-nest-2021.md
      - 2021-08:
        - translation/xfce-2021-08-02.md
        - translation/google-2021-08-04.md
        - translation/xfce-2021-08-17.md
        - translation/xfce-2021-08-17-02.md
        - translation/fedora-dpg-02.md
      - 2021-07:
        - translation/xfce-gsoc-2021.md
        - translation/opensuse-cc.md
        - translation/fedora-dpg.md
        - translation/github-2021-07-27.md

markdown_extensions:
  #启用工具提示
  - abbr
  - attr_list
  - pymdownx.snippets
  #启用警示标识
  - admonition
  - pymdownx.details
  - pymdownx.superfences 
  #启用注释
  - attr_list
  - md_in_html
  - pymdownx.superfences
  #启用按钮
  - attr_list
  #启用内容页
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  #启用脚注
  - footnotes
  #启用文本格式化
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  #启用图片
  - attr_list
  - md_in_html
  #启用列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search #启用搜索
  - blog:   #启用博客
      blog_toc: true
      authors_file: blog/.authors.yml
      post_readtime: false
  - tags:
      tags_file: about/tags.md
  - rss:
      abstract_chars_count: -1
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra:
  social:
    - icon: fontawesome/brands/suse
      link: https://forum.suse.org.cn/u/Aui/summary
    - icon: fontawesome/brands/fedora
      link: https://discussion.fedoraproject.org/u/bh
    - icon: fontawesome/brands/wikipedia-w
      link: https://zh.opensuse.org/User:White-poplar
    - icon: fontawesome/brands/github
      link: https://github.com/poplar-at-twilight

copyright: Copyleft; 2021-2024 Poplar_at_twilight